name: Run automated tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout todolist APP
        uses: actions/checkout@v3
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      
      - name: Checkout test repo
        run: git clone https://github.com/ccampos29/todoism-eafit-test.git

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Install tests deps
        run: |
          cd todoism-eafit-test
          npm ci

      - name: Install browsers
        run: npx playwright install --with-deps
      
      - name: Run playwright tests
        run: |
          cd todoism-eafit-tests
          npx playwright test todolist-spec.ts
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: todoism-eafit-test/playwirght-report
          retentation-days: 1
